DROP ROLE IF EXISTS bookmark_user;
DROP DATABASE IF EXISTS bookmarkr;

CREATE ROLE bookmark_user WITH LOGIN NOCREATEDB NOCREATEUSER UNENCRYPTED PASSWORD 'password';
CREATE DATABASE bookmarkr WITH OWNER=bookmark_user;