DROP ROLE IF EXISTS bookmrkr_user;
DROP DATABASE IF EXISTS bookmrkr;

CREATE ROLE bookmrkr_user WITH LOGIN CREATEDB NOCREATEUSER UNENCRYPTED PASSWORD 'password';
CREATE DATABASE bookmrkr WITH OWNER=bookmrkr_user;