# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 03:18
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20150626_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='type',
            field=models.CharField(choices=[('Link', 'Link'), ('Article', 'Article'), ('Image', 'Image'), ('Video', 'Video')], default='Link', max_length=2),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorful.fields.RGBColorField(colors=['#FFFFFF', '#E91E63', '#9C27B0', '#673AB7', '#3F51B5', '#2196F3', '#03A9F4', '#00BCD4', '#009688', '#4CAF50', '#8BC34A', '#CDDC39', '#FFEB3B', '#FFC107', '#FF9800', '#FF5722', '#795548', '#9E9E9E', '#607D8B', '#000000', '#FFFFFF'], null=True),
        ),
    ]
