# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160122_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='type',
            field=models.CharField(choices=[('Link', 'Link'), ('Article', 'Article'), ('Image', 'Image'), ('Video', 'Video')], default='Link', max_length=10),
        ),
    ]
